Make docker bind the TFTP server to the correct interface
kernelci/lava-docker pull request #117
Opened 2020-05-14 09:18 UTC by Rahix

With UDP, docker sometimes can't route packets to the correct address because the source address gets mangled (see moby/libnetwork#1729).  This happens indeterministically because by default the kernel uses some heuristics to decide which interface to use.  But in some rare circumstances, those can fail and a wrong source address is used.  This can be worked around by explicitly binding to a concrete interface instead of 0.0.0.0.

2020-05-14 09:21 UTC, Rahix commented
Cc: @patersonc

2020-05-20 07:17 UTC, montjoie requested changes
dispatcher_ip is optional so you must check if it is present

2020-05-20 08:04 UTC, Rahix commented
Makes sense, I've added the check.

2020-07-09 10:50 UTC, montjoie approved these changes

2020-07-09 16:47 UTC, merged