stick to 2017.11
kernelci/lava-docker pull request #15
Opened 2018-01-25 20:20 UTC by montjoie

Since LAVA packages are ephemeral, this patch permit to build a know release of LAVA.
In the same time, stick to 2017.11 as its a know working release for
lava-docker.

2018-01-29 16:00 UTC, khilman requested changes
The changelog needs more description about the changes.  e.g. no more packages installed, built from source (where do sources come from?)

the scripts/build-lava looks like it's duplicated.

2018-01-30 14:11 UTC, montjoie commented
I have added a comment in buildlava and modified commit message.

2018-02-01 19:01 UTC, khilman commented
Duplicating the script in git is a NAK for me.  We need to find a way to share that file.   Maybe a shared volume?

2018-02-01 19:49 UTC, khilman commented
Rather than duplicating this file in git, please create a single copy of the script in a top-level dir, and use `lavalab-gen.py` to copy it to each of the containers.

2018-02-02 14:13 UTC, montjoie commented
Updated with your last remark

2018-02-02 18:24 UTC, khilman approved these changes

2018-02-02 18:24 UTC, merged